module.exports = () => ({
    CARACTERES_INVALIDOS: ['*', '"', '\\', '/', '<', '>', ':', '|', '?'],
    MESES: (mes) => [ "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" ][mes - 1],
    FORMATO_DIA: "YYYY-MM-DD",
    SIMBOLOS: {
        sacar: "⊖",
        agregar: "⊕",
        volver: "↶",
        modificar: "✏️",
        opcional: "(opcional)",
    },
    TEMPLATE: {
        nota: {
            self: "Nota - Template",
            materia: "Definicion - Template",
            curso: "Nota curso - Template",
            investigacion: "Nota investigacion - Template",
            proyecto: "Nota proyecto - Template",
        },
        coleccion: {
            componente: "Componete - Template",
            estructuraDatos: "Estructura de datos - Template",
            distribucion: "Distribucion - Template",
            documentoLegal: "Documento legal - Template",
            funciones: {
                self: "Funcion - Template",
                libreria: "Libreria de funciones - Template",
                modulo: "Modulo de funciones - Template",
            },
            libro: "Libro - Template",
            paper: "Paper - Template",
            programa: "Programa - Template",
            receta: "Receta - Template",
            bloqueMatematica: "Bloque Matematica - Template",
        },
        seccion: "Seccion - Template",
        etapa: "Etapa - Template",
        seccionReferencia: "Seccion referencias - Template",
        referencias: {
            self: "Referencia - Template",
            general: "Referencias simple - Template",
            editar: "Editar referencia - Template",
        }
    },
    SECCIONES: {
        referencias: { nivel: 1, texto: "Referencias" },
        resumen: { nivel: 1, texto: "Resumen" },
        definicion: { nivel: 1, texto: "Definición" },
        resumenInvestigacion: { nivel: 2, texto: "Resumen" },
        progreso: { nivel: 1, texto: "Progreso" },
        informacion: { nivel: 1, texto: "Información" },
    },
    TAGS: {
        investigacion: {
            self: "investigación",
            indice: "índice",
        },
        carrera: {
            self: "carrera",
            informatica: "ingeniería-en-informática",
            electronica: "ingeniería-electrónica",
            datos: "licenciatura-en-ciencia-de-datos",
            fisica: "licenciatura-en-ciencias-físicas",
            matematica: "licenciatura-en-ciencias-matemáticas",
        },
        curso: {
            self: "cursos",
            curso: "curso",
        },
        materia: "materia",
        resumenMateria: "resumen-materia",
        resumenCurso: "resumen-curso",
        coleccion: {
            self: "colección",
            funciones: {
                self: "funciones",
                lenguajes: {
                    self: "lenguaje",
                    python: "Librerías-de-Python",
                    c: "Librerías-de-C",
                },
                libreria: "libreria",
                modulo: "modulo",
                funcion: "función",
            },
            bloqueMatematica: {
                self: "bloque-matematica",
                tema: "tema",
                subtema: "subtema",
            },
        },
        referencias: "referencia",
        proyecto: {
            self: "proyecto",
            investigacion: {
                self: "investigación",
                general: "proyecto-investigación",
            }, 
            practico: {
                self: "práctico",
                general: "proyecto-práctico"
            },
            juego: {
                self: "GDD",
                general: "game-design-documents",
            },
        },
        nota: {
            self: "nota",
            carrera: "facultad",
            investigacion: "investigacion",
            proyecto: "proyecto",
            curso: "curso",
        }
    },
    DIRECTORIOS: {
        imagenes: "img",
        temporal: "temp",
        referencias: "_referencias",
        investigacion: "investigación",
        curso: "cursos",
        proyectoPractico: "proyecto práctico",
        proyectoInvestigacion: "proyecto investigación",
        GDD: "game design documents",
        coleccion: {
            self: "colección",
            componentes: "componentes",
            bloquesMatematica: "teoremas, proposiciones y observaciones",
            dataStructures: "data structures",
            distribuciones: "distribuciones",
            documentos: "documentos",
            funciones: {
                self: "funciones",
                python: "Lenguaje Python",
                c: "Lenguaje C",
            },
            libros: "libros",
            papers: "papers",
            programas: "programas",
            recetas: "recetas",
        },
        carrera: {
            informatica: "ingeniería en informática",
            electronica: "ingeniería electrónica",
            datos: "licenciatura en ciencia de datos",
            fisica: "licenciatura en ciencias físicas",
            matematica: "licenciatura en ciencias matemáticas",
        },
        template: {
            self: "_template",
            referencias: "referencias",
        },
    },
    REFERENCIAS: {
        libro: "Libro",
        capituloLibro: "CapituloLibro",
        curso: "Curso",
        temaCurso: "CursoTema",
        paper: "Paper",
        youtube: "Youtube",
        web: "Web",
        wikipedia: "Wikipedia",
    },
    DATOS: {
        CARRERA: {
            estado: "estado",
            tags: "tags",
            planesDeEstudio: "planes",
            tieneCodigoLaMateria: "tieneCodigo",
        },
        MATERIA: {
            infoCuatri: "cuatri",
            referencias: "referencias",
            equivalencia: "equivalencia",
            tags: "tags",
        },
        INVESTIGACION: {
            estado: "estado",
            tags: "tags",
            dia: "dia",
            aliases: "aliases",
            referencias: "referencias",
        },
        CURSO: {
        },
        RESUMEN: {
            numero: "capitulo",
            parte: "parte",
            referencias: "referencias",
        },
        PROYECTO: {
            dia: "dia",
            estado: "estado",
            tags: "tags",
        },
        GDD: {
        },
        ARCHIVO: {
            etapa: "etapa",
            tags: "tags",
            dia: "dia",
            aliases: "aliases",
            referencias: "referencias",
        },
        PROGRESO: {
            dia: "dia",
            tags: "tags",
        },
        BLOQUES_MATEMATICA: {
            tema: {
                tags: "tags",
                numero: "capitulo",
                nombre: "nombreTema",
                obtenerTitulo: (tema) => `Tema de ${tema}`,
            },
            subtema: {
                tags: "tags",
                numero: "capitulo",
                nombre: "nombreSubtema",
                nota: {
                    self: "nota",
                    numero: "numero",
                    nombre: "nombre",
                    path: "path",
                    pathRelacionado: "pathRelacionado",
                },
                obtenerTitulo: (tema, subtema) => `${subtema} del tema ${tema}`,
            },
        },
        FUNCIONES: {
            lenguaje: {
                tags: "tags",
                nombre: "nombreLenguaje",
                temaInvestigacion: "temaInvestigacion",
                lenguajes: {
                    python: "Python",
                    c: "C",
                },
                keyLenguaje: (lenguaje) => lenguaje.toLowerCase(),
                obtenerTitulo: (lenguaje) => `Librerías del lenguaje de ${lenguaje}`,
            },
            libreria: {
                tags: "tags",
                nombre: "nombreLibreria",
                obtenerTitulo: (lenguaje, libreria) => `Librería ${libreria} de ${lenguaje}`,
            },
            modulo: {
                tags: "tags",
                nombre: "nombreModulo",
                obtenerTitulo: (lenguaje, libreria, modulo) => `Módulo ${modulo} de la librería ${libreria} en ${lenguaje}`,
            },
            funcion: {
                tags: "tags",
                firma: {
                    self: "firma",
                    nombreFuncion: "nombre",
                    descripcion: "descripcion",
                    parametros: {
                        self: "parametros",
                        nombreParametro: "nombre",
                        tipoDeDato: "type",
                        valorPorDefecto: "default",
                        descripcion: "descripcion",
                    },
                    return: {
                        self: "return",
                        tipoDeDato: "type",
                        descripcion: "descripcion",
                    },
                },
            },
        },
        REFERENCIAS: {
            numReferencia: "numReferencia",
            tipoCita: "tipoCita",
            aliases: "aliases",
            libro: {
                TITULO_OBRA: "tituloObra",
                SUBTITULO_OBRA: "subtituloObra",
                NOMBRE_AUTORES: "nombreAutores",
                ANIO: "anio",
                EDITORIAL: "editorial",
                EDICION: "edicion",
                VOLUMEN: "volumen",
                URL: "url",
                CAPITULOS: "capitulos",
            },
            capituloLibro: {
                NUMERO_CAPITULO: "numeroCapitulo",
                NOMBRE_CAPITULO: "nombreCapitulo",
                EDITORES: "editores",
                PAGINAS: "paginas",
            },
            curso: {
                NOMBRE_AUTORES: "nombreAutores",
                FECHA_CURSO: "fechaCurso",
                NOMBRE_CURSO: "nombreCurso",
                NOMBRE_PAGINA: "nombrePagina",
                URL: "url",
            },
            temaCurso: {
                NOMBRE_TEMA: "nombreTema",
                NUMERO_TEMA: "capitulo",
                PROFESORES: "profesores",
                PARTE_TEMA: "parte",
                CURSO: "curso",
            },
            paper: {
                AUTORES: "autores",
                TITULO_INFORME: "tituloInforme",
                SUBTITULO_INFORME: "subtituloInforme",
                ANIO: "anio",
                NOMBRE_REVISTA: "nombreRevista",
                VOLUMEN_REVISTA: "volumenRevista",
                PAGINAS: "paginas",
                NUMERO_INFORME: "numeroInforme",
                EDITORES: "editores",
                URL: "url",
                DOI: "doi",
            },
            web: {
                NOMBRE_AUTORES: "nombreAutores",
                FECHA_PUBLICACION: "fechaPublicacion",
                TITULO_ARTICULO: "tituloArticulo",
                NOMBRE_PAGINA: "nombrePagina",
                URL: "url",
            },
            wiki: {
                NOMBRE_ARTICULO: "nombreArticulo",
                FECHA: "fecha",
                URL: "url",
            },
            youtube: {
                NOMBRE_VIDEO: "nombreVideo",
                NOMBRE_CANAL: "nombreCanal",
                FECHA: "fecha",
                URL: "url",
            },
            salir: "salir",
        },
    },
    ETAPAS: {
        sinEmpezar: "sin-empezar",
        empezado: "empezado",
        ampliar: "ampliar",
        terminado: "terminado",
    },
    CREAR_SECCION: {
        materia: "Materia",
        resumenMateria: "Resumen materia",
        curso: "Curso",
        resumenCurso: "Resumen curso",
        investigacion: "Investigación",
        proyectoPractico: "Proyecto práctico",
        proyectoInvestigacion: "Proyecto Investigación",
        juego: "GDD",
        coleccion: {
            funciones: {
                libreria: "Libreria funciones",
                modulo: "Módulo funciones"
            },
            bloqueMatematica: {
                tema: "Tema bloque matemática",
                subtema: "Subtema bloque matemática",
            },
        },
    },
    BLOQUES_MATEMATICA: {
        bloques: {
            teorema: "teorema",
            observacion: "observacion",
            proposicion: "proposicion",
            corolario: "corolario",
            demostracion: "demostracion",
        },
        teorema: {
            callout: "teorema",
            nombre: "Teorema",
            reducido: "teo",
        },
        observacion: {
            callout: "observacion",
            nombre: "Observación",
            reducido: "obs",
        },
        proposicion: {
            callout: "proposicion",
            nombre: "Proposición",
            reducido: "prop",
        },
        corolario: {
            callout: "corolario",
            nombre: "Corolario",
            reducido: "cor",
        },
        demostracion: {
            callout: "demostracion",
            nombre: "Demostración",
        }
    },
});