module.exports = () => ({
    CARACTERES_INVALIDOS: ['*', '"', '\\', '/', '<', '>', ':', '|', '?'],
    MESES: (mes) => [ "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" ][mes - 1],
    TEMPLATE: {
        nota: "Nota - Template",
        seccion: "Seccion - Template",
    },
    SECCIONES: {
        referencias: { nivel: 1, texto: "Referencias" },
        resumen: { nivel: 1, texto: "Resumen" },
        definicion: { nivel: 1, texto: "Definición" },
    },
    TAGS: {
        investigacion: "índice",
        carrera: "carrera",
        materia: "materia",
        resumen: "resumen",
        curso: "cursos",
        coleccion: "colección",
        referencias: "referencia",
        bloqueMatematica: {
            self: "bloque-matematica",
            tema: "tema",
            subtema: "subtema",
        },
        proyecto: {
            self: "proyecto",
            investigacion: "investigación",
            practico: "práctico",
            juego: "GDC",
        },
        nota: {
            self: "nota",
            carrera: "facultad",
            investigacion: "investigacion",
            proyecto: "proyecto",
            curso: "curso",
        }
    },
    DIRECTORIOS: {
        referencias: "_referencias",
        investigacion: "investigación",
        curso: "cursos",
        proyectoPractico: "proyecto práctico",
        proyectoInvestigacion: "proyecto investigación",
        GDD: "game design documents",
        coleccion: {
            self: "colección",
            componentes: "componentes",
            bloquesMatematica: "teoremas, proposiciones y observaciones",
            dataStructures: "data structures",
            distribuciones: "distribuciones",
            documentos: "documentos",
            funciones: "funciones",
            libros: "libros",
            papers: "papers",
            programas: "programas",
            recetas: "recetas",
        },
        carrera: {
            informatica: "ingeniería en informática",
            electronica: "ingeniería electrónica",
            datos: "licenciatura en ciencia de datos",
            fisica: "licenciatura en ciencias físicas",
            matematica: "licenciatura en ciencias matemáticas",
        },
    },
    REFERENCIAS: {
        libro: "Libro",
        capituloLibro: "CapituloLibro",
        curso: "Curso",
        temaCurso: "CursoTema",
        paper: "Paper",
        youtube: "Youtube",
        web: "Web",
        wikipedia: "Wikipedia",
    },
    DATOS: {
        REFERENCIAS: {
            numReferencia: "numReferencia",
            tipoCita: "tipoCita",
            aliases: "aliases",
            libro: {
                TITULO_OBRA: "tituloObra",
                SUBTITULO_OBRA: "subtituloObra",
                NOMBRE_AUTORES: "nombreAutores",
                ANIO: "anio",
                EDITORIAL: "editorial",
                EDICION: "edicion",
                VOLUMEN: "volumen",
                URL: "url",
                CAPITULOS: "capitulos",
            },
            capituloLibro: {
                NUMERO_CAPITULO: "numeroCapitulo",
                NOMBRE_CAPITULO: "nombreCapitulo",
                EDITORES: "editores",
                PAGINAS: "paginas",
            },
            curso: {
                NOMBRE_AUTORES: "nombreAutores",
                FECHA_CURSO: "fechaCurso",
                NOMBRE_CURSO: "nombreCurso",
                NOMBRE_PAGINA: "nombrePagina",
                URL: "url",
            },
            temaCurso: {
                NOMBRE_TEMA: "nombreTema",
                NUMERO_TEMA: "capitulo",
                PROFESORES: "profesores",
                PARTE_TEMA: "parte",
                CURSO: "curso",
            },
            paper: {
                AUTORES: "autores",
                TITULO_INFORME: "tituloInforme",
                SUBTITULO_INFORME: "subtituloInforme",
                ANIO: "anio",
                NOMBRE_REVISTA: "nombreRevista",
                VOLUMEN_REVISTA: "volumenRevista",
                PAGINAS: "paginas",
                NUMERO_INFORME: "numeroInforme",
                EDITORES: "editores",
                URL: "url",
                DOI: "doi",
            },
            web: {
                NOMBRE_AUTORES: "nombreAutores",
                FECHA_PUBLICACION: "fechaPublicacion",
                TITULO_ARTICULO: "tituloArticulo",
                NOMBRE_PAGINA: "nombrePagina",
                URL: "url",
            },
            wiki: {
                NOMBRE_ARTICULO: "nombreArticulo",
                FECHA: "fecha",
                URL: "url",
            },
            youtube: {
                NOMBRE_VIDEO: "nombreVideo",
                NOMBRE_CANAL: "nombreCanal",
                FECHA: "fecha",
                URL: "url",
            },
            salir: "salir",
        },
        ARCHIVO: {
            referencias: "referencias",
            etapa: "etapa",
            tags: "tags",
            dia: "dia",
            aliases: "aliases",
        },
        BLOQUES_MATEMATICA: {
            tema: {
                tags: "tags",
                numero: "capitulo",
            },
            subtema: {
                tags: "tags",
                numero: "capitulo",
                nota: {
                    self: "nota",
                    numero: "numero",
                    nombre: "nombre",
                    path: "path",
                },
            },
        },
    },
    ETAPAS: {
        sinEmpezar: "sin-empezar",
        empezado: "empezado",
        ampliar: "ampliar",
        terminado: "terminado",
    },
    NOMBRE_SECCIONES: {
        facultad: "Facultad",
        curso: "Curso",
        investigacion: "Investigación",
        proyectoPractico: "Proyecto Práctico",
        proyectoInvestigacion: "Proyecto Investigación",
        GDD: "GDD",
    },
    BLOQUES_MATEMATICA: {
        teorema: {
            callout: "teorema",
            nombre: "Teorema",
            reducido: "teo",
        },
        observacion: {
            callout: "observacion",
            nombre: "Observación",
            reducido: "obs",
        },
        proposicion: {
            callout: "proposicion",
            nombre: "Proposición",
            reducido: "prop",
        },
        template: {
            tema: "Bloque Matematica Tema - Template",
            subtema: "Bloque Matematica Subtema - Template",
        },
    },
});